default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: dbpassword
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: i-manage_development

test:
  <<: *default
  database: i-manage_test

production:
  <<: *default
  database: i-manage_production
  username: i-manage
  password: <%= ENV['I-MANAGE_DATABASE_PASSWORD'] %>
